### ISSUE TITLE
API authentication failed with version 1.7.1 and higher

### ISSUE THREAD

**Issue by billerickson** [Kit/convertkit-wpforms#61]
Over the past few weeks I've had clients report that their email signups are no longer making it to ConvertKit. 

It says it is "Connected" in WPForms > Settings > Integrations:

![screenshot](https://p198.p4.n0.cdn.zight.com/items/BluPXm0O/b035578b-6b98-45bb-adcf-e8da6a81a5fc.jpg?v=%220ff9a96f0159f75e76e2d9cd89350219%22)

But when I enable logging, it shows the API authentication failed:

![screenshot](https://p198.p4.n0.cdn.zight.com/items/ApuqKqbo/0cce9779-42f2-4637-8207-930d36efe616.jpg?source=viewer&v=%222894282f35f60c33a16c99dad3752635%22)

Clients have noted that the forms were working up until around July 16th, which seems to coincide with the 1.7.1 release.

Our solution so far has been to:
- Go to WPForms > Settings > Integrations > ConvertKit
- Click "Disconnect", then "Add New Account" and reconnect to ConvertKit
- Go through each form on the site and reconnect them to ConvertKit.

At a minimum, can the plugin display an error message in the WP backend telling clients that their ConvertKit connection doesn't work and encourages them to reconnect it.

Preferably, could the plugin fix whatever issue is causing this without requiring publishers to reconnect to ConvertKit and reconnect all their forms?

[edit] Could this have something to do with the new API token expiry?

![screenshot](https://p198.p4.n0.cdn.zight.com/items/nOu264om/22e18d84-85c0-411b-89e1-c52949f04ece.png?source=viewer&v=%22e1d19cf6ea979b314de3a94621dcc9f7%22)

**Comment by n7studios** [comment]
@billerickson The `convertkit_api_refresh_token` _should_ be fired when our API class [detects the access token expired](https://github.com/ConvertKit/convertkit-wordpress-libraries/blob/main/src/class-convertkit-api-v4.php#L1466), and [our tests](https://github.com/ConvertKit/convertkit-wpforms/blob/main/tests/wpunit/APITest.php#L71) suggest this works - but it looks like this isn't happening, resulting in the log errors and needing to re-connect.

I'll review and advise when resolved, hopefully by the end of Tuesday. Thanks!

**Comment by n7studios** [comment]
@billerickson On sites where you're seeing this issue, is the connected ConvertKit account connected on multiple, different WordPress sites using this Plugin?

**Comment by billerickson** [comment]
@n7studios No, on all the sites that have had this issue, it's a single ConvertKit account connected to a single website.

**Comment by n7studios** [comment]
@billerickson And none of the affected sites have a staging/development copy? Apologies if this seems an obvious question - this may be due to how tokens are assigned to redirect URI's, so trying to figure out where a fix might need to be applied here. Thanks!

**Comment by billerickson** [comment]
Yes, the affected sites have staging environments. I'm not sure if they are being actively used, but all our clients have staging environments for when we're testing theme changes.

**Comment by n7studios** [comment]
1.7.4, released today, will only automatically refresh an expired access token on a production site (using `wp_get_environment_type`). There may still be an issue where the same ConvertKit creator account is used across two or more production sites, which is something we're aware of and looking at. Thanks!
